{% set name = "srsly" %}
{% set version = "2.4.8" %}
{% set sha256sum = "b24d95a65009c2447e0b49cda043ac53fecf4f09e358d87a57446458f91b8a91" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-skip-deprecation-test.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.1,<0.30.0                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.29.1,<0.30.0
  run:
    - python
    - catalogue >=2.0.1,<2.1.0

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pytest
    - pytz
    - mock
    - numpy >=1.15.0
    - psutil
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: http://github.com/explosion/srsly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python

  doc_url: https://github.com/explosion/srsly
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
