{% set version = "2.5.1" %}

package:
  name: srsly
  version: {{ version }}

source:
  url: https://github.com/explosion/srsly/archive/refs/tags/release-v{{ version }}.tar.gz
  sha256: 1ad1ae8c933c114e0b5c0374bec274f072d707ba94b46c8e21ffba7e6c06ee8a
  patches:
    - patches/0001-skip-deprecation-test.patch
    - patches/0002-Use-upstream-cloudpickle.patch
    - patches/0003-Use-upstream-ujson.patch
    - patches/0004-Update-JSON-tests-spaces-after-keys-by-default.patch
    - patches/0005-allow-python-3.14.patch

build:
  number: 2


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
  run:
    - python
    - catalogue >=2.0.1,<2.1.0
    - cloudpickle >=2.2.0
    - ujson >=1.35

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pytest
    - pytz
    - mock
    - numpy >=1.15.0
    - psutil
  commands:
    - python -m pytest --tb=native --pyargs srsly

about:
  home: http://github.com/explosion/srsly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python

  doc_url: https://github.com/explosion/srsly
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - conda-forge/spacy
