{% set name = "srsly" %}
{% set version = "2.5.1" %}
{% set sha256sum = "ab1b4bf6cf3e29da23dae0493dd1517fb787075206512351421b89b4fc27c77e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-Add-patch-to-skip-deprecation-warning-test-for-yaml.patch
    - patches/0002-Use-upstream-cloudpickle.patch
    - patches/0003-Use-upstream-ujson.patch
    - patches/0004-Update-JSON-tests-spaces-after-keys-by-default.patch

build:
  number: 1


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.1,<0.30.0                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.29.1,<0.30.0
  run:
    - python
    - catalogue >=2.0.1,<2.1.0
    - cloudpickle >=2.2.0
    - ujson >=1.35

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pytest
    - pytz
    - mock
    - numpy >=1.15.0
    - psutil
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: http://github.com/explosion/srsly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python

  doc_url: https://github.com/explosion/srsly
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - conda-forge/spacy
