{% set name = "srsly" %}
{% set version = "2.3.0" %}
{% set sha256sum = "f994a266f6e547c8ffe803cb90baed7ca566831f924e0491402564ba0d185e66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k or py35]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
  run:
    - python

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pytest
    - pytz
    - mock
    - numpy >=1.15.0
  commands:
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: http://github.com/explosion/srsly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python

  doc_url: https://github.com/explosion/srsly
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
